### ISSUE TITLE
Voice pitch changes in a streaming application 

### ISSUE THREAD

**Issue by amantalion** [avaneev/r8brain-free-src#10]
Hi, thanks for the great library! 

I tested the library in a non-streaming application, and everything worked fine (reading from one file, converting sr, writing the resulting buffer to another file). 

However, when I switched to a streaming application, I noticed that the library alters the voice pitch - makes the voice pitch high when converting the sampling rate to a higher rate (16KHz->48KHz) and low when converting the sampling rate to a lower rate (48KHz->16KHz).

I looked at everything and cannot find the bug in my code. Do you know by any chance if anything in the library might cause this behavior? 

Thank you so much!

**Comment by avaneev** [comment]
Sample rate conversion alone won't preserve pitch. You should look for pitch-shifting algorithms.

**Comment by avaneev** [comment]
Or if you are upsampling 16kHz to 44.1kHz and playing back at 16kHz, the pitch will be lower. You should playback it at 44.1kHz as well.
