### ISSUE TITLE
Will this work with format 16bit format?

### ISSUE THREAD

**Issue by rizhang2** [avaneev/r8brain-free-src#11]
I'm using the DLL in my windows project and I'm confused that the "process" function only takes in a buffer in the form of a pointer to a double. What I really want to do is pass in a pointer to 16 bit integers. Would I need to convert these 16 bit integers to doubles?

FYI I'm linking this to a rust project, so doubles are represented as 64bit floats.

**Comment by avaneev** [comment]
Yes, you'll need to convert to 64-bit doubles. It's not possible to perform sample rate conversion in 16-bit integer resolution. After  conversion, to transform back to 16-bits you'll need to apply clipping to the output, and dithering noise. These are DSP basics.

**Comment by rizhang2** [comment]
I see, so it sounds like this library really is just meant for floating point formats?

Are there libraries out there that can perform clipping and dithering noise? All I need is to be able to convert from 48kHz 16bit integer to 44.1kHz 16bit integer.

**Comment by rizhang2** [comment]
When I convert the audio samples to doubles and pass it into `process`, would the new samples be suitable to be passed into an Audio Engine that takes in 32bit float samples?

**Comment by avaneev** [comment]
Yes, converting doubles to floats is generally safe. Only if you convert doubles to integers, you need clipping and dithering.

This library is meant for floating point formats only, usually used as a part of a bigger processing topology.

**Comment by rizhang2** [comment]
I see, thanks for the reply! It seems like this library fits my needs because I will need to SRC from an audio stream. I have some more silly questions.

When converting a 16bit int sample to a double sample so I can pass the samples to this library, would I just cast the 16bit to a double, or would I have to cast it to a double and then divide by 65536. I read somewhere floating point representation for audio samples needs to be between -1 and 1.

**Comment by avaneev** [comment]
This SRC library does not depend on input value scaling - you may pass values without normalization.
