### ISSUE TITLE
[REQ] Foobar2000 plugin

### ISSUE THREAD

**Issue by MarcoRavich** [avaneev/r8brain-free-src#14]
Hi there, it would be extremely cool to have a version of this great resampler for FB2K users (me too).

- https://www.foobar2000.org/
- https://www.foobar2000.org/components
- https://hydrogenaud.io/index.php?board=28.0

Hope that inspires !

**Comment by avaneev** [comment]
Thanks for the message, but creating some "custom versions" is beyond my plans. I think it's Foobar that can incorporate r8brain, not myself. Audirvana for example finally incorporated r8brain.

**Comment by MarcoRavich** [comment]
Here we go, finally:
https://foobar.hyv.fi/?view=foo_dsp_r8brain_resampler
