### ISSUE TITLE
CMake Capability

### ISSUE THREAD

**Issue by benjamin-huynh** [avaneev/r8brain-free-src#15]
I am working on a project right now that utilizes the R8Brain library, and it involves with CMake build. Do you intend to have a CMake build for this library or have any Conan recipes for it? Conan currently only has a version 4.6 recipe, but I would like to use the most updated version (5.2).

**Comment by avaneev** [comment]
There's little to "build" in this library, you basically need to compile and include a single cpp file, the library is "inline" for the most part. So, I do not see a need in CMake build.
