### ISSUE TITLE
Unknown type name 'IppsFFTSpec_R_64f' when R8B_IPP is set to 1

### ISSUE THREAD

**Issue by zgerrard** [avaneev/r8brain-free-src#16]
Hi, I get `Unknown type name 'IppsFFTSpec_R_64f'` when I define `#define R8B_IPP 1`, as instructed in the README. Please, could you help me to resolve this error? Thank you.

**Comment by avaneev** [comment]
You need Intel IPP headers and libraries to use R8B_IPP 1 macro.

Make sure you've added to r8bconf.h these or similar include statements:
	#include <ippcore.h>
	#include <ipps.h>

You also need to call ippInit() before using r8brain resampler.

**Comment by zgerrard** [comment]
Thanks so much @avaneev. Quick question: do you know if PFFFT is faster than Ooura FFT? Also, Ooura is used by default, right?

**Comment by avaneev** [comment]
Ooura FFT is used by default. Using PFFFT_DOUBLE is faster than Ooura FFT.
