### ISSUE TITLE
Investigate a DSD decimator stage for DSD to PCM conversion

### ISSUE THREAD

**Issue by kode54** [avaneev/r8brain-free-src#18]
I implemented a little benchmark here:

https://gist.github.com/kode54/0912aa2c4fe339913dd5397cea06eab5

I found the decimator plus resampler was approximately 40% faster than just converting the DSD to a series of ±1.0 samples and downsampling it directly. I'm not sure of the licensing of the filter I ended up using, though, or whether it's normalized to a proper volume level relative to input.

**Comment by avaneev** [comment]
Thanks. I do not quite understand relation of your use-case and r8brain-free-src, though.

**Comment by kode54** [comment]
I'm using it in an audio player that happens to support DSD playback as PCM.

**Comment by avaneev** [comment]
It's possible that decimator in your case is more efficient for 1-bit streams than full resampling.

**Comment by kode54** [comment]
Quite possibly. Although it's very little difference overall. The performance is the difference between 600ms and 1000ms for downsampling 33554432 (32 * 1024 * 1024) bytes worth of random DSD (8 times that many samples), from the DSD64 sample rate to 48kHz. In my audio player, in practice, the majority of the overhead is going to be coming from the WavPack DSD decoding, and not from the resampler. I haven't even tested FFmpeg's DST support, and I don't think it's going to work for real time playback, and even if it does, it's hard coded to do the decimation for me, whether I want it or not.

**Comment by avaneev** [comment]
Thanks for sharing your experience. But I do not see how I can help here.

**Comment by kode54** [comment]
I was sharing in case a similar decimator is in any way useful to the library or users of the library. It's probably not, though.

I did drop you a note linking to my application of the resampler, though. Sorry for the long winded notice, I kind of got carried away.

**Comment by avaneev** [comment]
No problem.

**Comment by avaneev** [comment]
I'll add that e.g. `CDSPHBDownsampler.h` can probably be implemented for 1-bit streams, squeezing some performance out of the fact the stream is 1-bit (only -1 and 1 sample values), but it will work only for 1-bit streams, so not really flexible in r8brain-free context.

**Comment by avaneev** [comment]
FYI, r8brain-free-src 6.2 features an improved downsampling performance. It may not still be as fast as a specialized 1-bit downsampler, but maybe much closer to it now.

**Comment by kode54** [comment]
Thanks, I've been neglecting to follow updates.
