### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by isgursoy** [avaneev/r8brain-free-src#19]
`corrupted size vs. prev_size while consolidating`
![1](https://user-images.githubusercontent.com/2170245/161399563-ebb1b14c-1c19-4cdc-b17a-db4fc67c564d.png)

Probably I am getting crash upon destruction of static filters in r8base.cpp. I am using v5.6.

**Comment by isgursoy** [comment]
It was my mistake.

**Comment by avaneev** [comment]
No problem!

**Comment by isgursoy** [comment]
For reference; mistake was having same symbols from different libraries.
