### ISSUE TITLE
Power of two FFT resampler affects volume level

### ISSUE THREAD

**Issue by kode54** [avaneev/r8brain-free-src#22]
The power of two FFT resampler increases or decreases the volume level relative to the resampling ratio. Doubling the sample rate doubles the volume, and halving the sample rate halves the volume.

If this is affected by the FFT chosen, then it is specific to PFFFT double and my new vDSP implementation.

It doesn't seem to affect the convolver used by the non-integer ratios, so it doesn't appear to apply to FFT conversions that start and end at the same filter bank size.

**Comment by avaneev** [comment]
Must be your vDSP implementation. Please see CDSPFIRFilter.h:507. The getInvMulConst() should return a correct multiplier, it's dependent on FFT code.

**Comment by kode54** [comment]
It happens with your PFFFT implementation as well.

**Comment by avaneev** [comment]
> It happens with your PFFFT implementation as well.

Are you using CDSPBlockConvolver.h in isolated manner? If so, you have to request filter with a correct precomputed ReqGain.

**Comment by kode54** [comment]
I am merely using CDSPResampler24.

Edit: I am converting 44100 to 48000 with no resulting gain change, but doubling to 88200 or increasing further to 96000 results in doubled gain.

Edit 2: Similarly, reducing DSD from 352800 to 96000Hz results in a signal which is twice as loud as reducing it to 44100Hz or 48000Hz.

Edit 3: I verified this behaves identically between the default FFT, PFFFT, and my new implementation, which are all double precision.

**Comment by avaneev** [comment]
Sorry, I do not understand. This does not happen here, with Ooura, PFFFT and PFFFT_DOUBLE. Also, nobody else reported such serious issue. Make sure you are not applying some gain yourself in the conversion code.

**Comment by kode54** [comment]
Hmm. That's strange, I'm not applying any gain in the resampler other than whatever it's doing on its own. Though I am applying a convolver step on the output, using a 48 kHz impulse I resample using r8b. I can disable that, but it doesn't have any major effect on the gain.

**Comment by kode54** [comment]
Okay, scratch that, it's my stupid convolver. All I'm doing with it is upsampling the impulse that it uses, which apparently doubles it in volume?

**Comment by avaneev** [comment]
Upsampling won't change the "acoustical" volume of the impulse, but when used as an impulse response, gain correction may be needed.

**Comment by kode54** [comment]
Yeah, sorry to bother you. I didn't realize it was my convolution effect. Adding a vDSP_vsdiv by the sample ratio (increase on downsample, decrease on upsample) normalized the volume levels.

Really weird issue to find with my code. I should have eliminated it in the first place before using my player to test whether your resampler was causing an issue.

That's two for two nonsense issues I've raised with you. Oops.

I will still attempt to file a PR for the vDSP implementation, which does work like it should.

**Comment by avaneev** [comment]
No problem.
