### ISSUE TITLE
Heap Curroption Exception with PFFFT when the global static list of objects is freed

### ISSUE THREAD

**Issue by unevens** [avaneev/r8brain-free-src#4]
Greetings!

When using PFFFT, the destructor of `CFixedBuffer<float> work`, defined at line 344 of `CDSPRealFFT.h`, will throw `Invalid address specified to RtlValidateHeap` on Windows, compiled with Visual Studio 2019, and `free: invalid pointer` on Linux compiled with GCC 8.3.0 or Clang 7.0.1. 
I didn't test on other platforms.

Here is some code to reproduce the isssue:

```cpp
#define R8B_PFFFT 1
#include "CDSPResampler.h"

int main(){
    r8b::CDSPResampler24 resampler(1.0, 2.0, 256);
    return 0;
}
```

**Comment by avaneev** [comment]
I'm unfortuntately cannot get this code to trap in Intel C++ Compiler.

**Comment by avaneev** [comment]
I've checked `CFixedBuffer` operation and it does perform correctly.

**Comment by unevens** [comment]
I'm sorry but I don't have access to the Intel Compiler. 

Anyway I experience this issue on Visual Studio, Clang and GCC.

Maybe I'm missing something? Here is a quick video reproducing the issue: https://youtu.be/e2hmsO06eyA

**Comment by avaneev** [comment]
I can't get your example to crash even in LLVM.

**Comment by avaneev** [comment]
You should probably include "r8bbase.h" as well.

**Comment by unevens** [comment]
I tried including also "r8bbase.h", but it does not change the outcome. https://www.youtube.com/watch?v=5lQ6E2LNjk0

**Comment by avaneev** [comment]
Could you read the code and debug what is wrong?

**Comment by avaneev** [comment]
One option is that you are using a custom memory manager which gets freed before static objects are deinitialized.

**Comment by unevens** [comment]
I am not doing anything except what I've shown you in the videos. 

I hoped you would had a better chance than me at tracking down where the heap corruption happens, since you know the codebase.

It's so puzzling to me that you can't reproduce this issue. I will investigate more, but right now I don't have much time to put into it.

Thank you for your feedback anyway - and for your amazing library, that goes without saying!

**Comment by unevens** [comment]
## Solution: define `R8B_PFFFT` using preprocessor definitions, **NOT** in an header. 

That was an oversight on my part, as  the library is not header-only. I sent you all the videos with my detailed setup hoping such a trivial error would be easy to spot. I guess you didn't really tried to replicate my setup, but just defined `R8B_PFFFT` in yours, so you weren't able to replicate the issue. Anyway, my fault to begin with. 

## What was happening

If `R8B_PFFFT` is defined in an header, this code in `CDSPRealFFT` gets compiled in both ways and all kind of nasty things happen.
```c++
	#elif R8B_PFFFT
		PFFFT_Setup* setup; ///< PFFFT setup object.
			///<
		CFixedBuffer< float > work; ///< Working buffer.
			///<
	#else // R8B_PFFFT
		CFixedBuffer< int > wi; ///< Working buffer (ints).
			///<
		CFixedBuffer< double > wd; ///< Working buffer (doubles).
			///<
	#endif // R8B_IPP
```
For example with the memory corruption error I got, the debugger shows that destructor of `CDSPRealFFT` tries to destroy `work`. So the destructor has been compiled with `R8B_PFFFT`. But the object does not contain `work`. It contains `wi` and `wd`. So the object has not been compiled with `R8B_PFFFT`. When the destructor tries to destroy `work`, it triggers an `invalid pointer` error.

**Comment by avaneev** [comment]
Thanks for exploring the issue. Defines should be put but in the beginning of `r8bconf.h` or globally in the project build - this is explicitly mentioned on the description page. This way it works without issues.
