### ISSUE TITLE
Passing nullptr to memcpy in realloc

### ISSUE THREAD

**Issue by jkuszmaul** [avaneev/r8brain-free-src#5]
At the following line:
https://github.com/avaneev/r8brain-free-src/blob/62ae865432bf6f058f9c7b5094d3ee638d76e028/r8bbase.h#L348

There are conditions under which you end up passing nullptr to memcpy, which is undefined behavior (see https://en.cppreference.com/w/cpp/string/byte/memcpy) even when the size of the buffer being copied is zero.

This occurs when constructing a basic resampler, e.g. `r8b::CDSPResampler16 resampler(22050, 48000, 1000);` causes a nullptr to be passed to `memcpy`. 

I observed this when running this using clang's [UndefinedBehaviorSanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html). I do not know if there are other spots with similar types of undefined behavior, but this was the first that it crashed on.

**Comment by avaneev** [comment]
Thanks for the notice, I've fixed this out-of-spec behavior.
