### ISSUE TITLE
Conan: Building as Dynamic Library on Windows

### ISSUE THREAD

**Issue by johanneskares** [avaneev/r8brain-free-src#7]
I added r8brain-free-src as a package on conan, one of the most common package managers for C++

https://github.com/conan-io/conan-center-index/pull/2536

Building a dynamic library on Windows failed, even with cmake option `WINDOWS_EXPORT_ALL_SYMBOLS` because that doesn't work for global static variables in the cpp.  (See comments on Conan-Center-Index PR)

**Comment by avaneev** [comment]
I do not think I can help here, on my own compiler configuration the build process works fine.

You have to export these symbols:
`r8b_create`
`r8b_delete`
`r8b_clear`
`r8b_process`

and add `r8bbase.cpp` to the build process, possibly define the R8B_PFFFT=1 globally, for performance reasons.

Static variables should be included into DLL by the compiler automatically.

**Comment by johanneskares** [comment]
ahh, I guess my mistake was to try to make C++ API the API of the dynamic lib, so basically just compiling `r8bbase.cpp` into a dll and using the headers for everything else. To use the library cross-platform as static and dynamic lib, would you always recommend using the C-API of the dll folder? Conan packages usually have one common API for all platforms.

Or as an alternative suggestion, wouldn't it make sense to make the complete library header-only. There's not much being compiled in the one cpp file and there would be a way of putting the static variables into the header-only code:
https://stackoverflow.com/a/11711082

**Comment by avaneev** [comment]
Sorry for the delay with my reply. I do really think if you have a C++ compiler you can just use the C++ code directly, it compiles pretty fast. DLL is meant for non-C++ users. I have not provided a way to build a static/dynamic library interchangeably, this wasn't tested by me at all.

The idea of "inline" initialization is great, but is not very backwards-compatible. For example, I still use VS2008 myself.
