### ISSUE TITLE
MSVC warning: redefinition of _USE_MATH_DEFINES

### ISSUE THREAD

**Issue by jeychenne** [avaneev/r8brain-free-src#9]
This is a minor thing, but the following line:

https://github.com/avaneev/r8brain-free-src/blob/15b3fda763ab5d4a4ececa233e93e0e55b7a705b/pffft.cpp#L70

should probably be:

```
#ifndef _USE_MATH_DEFINES
#  define _USE_MATH_DEFINES
#endif
```

**Comment by avaneev** [comment]
Thanks for noticing. PFFFT is not my code, but indeed `#ifndef` is desirable in case this define was already defined in a project. I'll update PFFFT.
